name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, sit, ppt, prd)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest

    # ‚úÖ All terraform commands will run from iac/
    defaults:
      run:
        working-directory: iac

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

        # üîπ Step 1: Create ZIP
      - name: Zip Lambda
        run: |
          cd src/lambda
          zip -r lambda.zip .
          ls -la   # optional debug

      # 2Ô∏è‚É£ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # 3Ô∏è‚É£ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4Ô∏è‚É£ Build Lambda package
      - name: Build Lambda package
        run: |
          cd ../src/lambda
          zip -r lambda.zip .
          mv lambda.zip ../../iac/

      # 5Ô∏è‚É£ Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6Ô∏è‚É£ Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7Ô∏è‚É£ Terraform Plan
      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file="environment/${{ github.event.inputs.environment || 'dev' }}.tfvars"

      # 8Ô∏è‚É£ Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply \
          -var-file="environment/${{ github.event.inputs.environment || 'dev' }}.tfvars" \
          -auto-approve
